### ISSUE TITLE
Installation location

### ISSUE THREAD

**Issue by Chefkeks** [encrypt0r/permadelete#30]
Hi there!

just discovered this great app to safely/securely delete files and folders and I know it's still beta, but wanted to let you know that currently I can only use the portable version 😞 
The reason is that for security all my stuff is running under a "normal"/standard/non-administrator account. Since the installation requires administrative rights (I'm running Windows 10, 1703, Enterprise x64 with UAC enabled, default UAC level) and the installation location cannot be changed, permadelete is then installed under %appdata% of the administrator account. When trying to open it then as my normal user, the app cannot be opened since the installation location is not accessible for/from my normal/standard user account. So currently I can only use the portable version.

My suggestion therefore is to install it to %ProgramFiles% instead, so all users can access it 😉 
In case this would lead to other issues, then you could e.g. build the setup so that it can be executed as normal/standard/non-admin user as well and the app then installs to %appdata% of the current user instead of the admin account.

Thanks in advance 😃 
Michael

PS: Would also love to see a .msi installer instead of the classic .exe installer

**Comment by encrypt0r** [comment]
@Chefkeks Thanks! To be honest, I hadn't realized that you can't install Permadelete on a standard account. Thanks for the tip. I have added [a standard installer](https://github.com/encrypt0r/permadelete/releases/tag/v0.5.1-beta) option. I have added it as a separate options so that it does not mess with current links. But from the next release on, the standard installer option will be the default one.

**Comment by Chefkeks** [comment]
Thanks for the quick addition of a standard installer 👍 
Closing this issue since with the standard installer everything's fine now 😁
